### ISSUE TITLE
resolver config race condition when concurrent processes

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#158]
I expect `ziti-edge-tunnel` is intended to be run one-process-per-device, but there's nothing to lock out concurrent processes and running a second instance will destructively manage the resolver config installed by the first instance. 

Potential approaches to lock out include:
* refuse to run if not the first process with the same command name
* refuse to run if default or configured locking dir exists (mkdir is atomic on most filesystems)
* refuse to run if default or configured IPC socket exists

**Comment by scareything** [comment]
ziti-edge-tunnel can execute concurrently without destroying resolver configuration _as long as the host operating system supports concurrent DNS configurations_, such as `systemd-resolved`

You do need to make sure that the DNS server IP ranges don't overlap:

- shell 1:

        $ sudo ziti-edge-tunnel run -i id1.json

- shell 2:

        $ sudo ziti-edge-tunnel run -i id2.json -d 192.168.0.0/16

- shell 3:

        $ ip link list | grep tun
        5: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500
        6: tun1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500
        $ resolvectl 
        Global
               Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
        resolv.conf mode: stub

        Link 2 (enp0s5)
            Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
                 Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
        Current DNS Server: 10.211.55.1
               DNS Servers: 10.211.55.1
                DNS Domain: localdomain

        Link 5 (tun0)
            Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
                 Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
        Current DNS Server: 100.64.0.2
               DNS Servers: 100.64.0.2

        Link 6 (tun1)
            Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
                 Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
        Current DNS Server: 192.168.0.2
               DNS Servers: 192.168.0.2

**Comment by qrkourier** [comment]
Thanks, Shawn. I meant to bring attention to the fact that `ziti-edge-tunnel` fails silently when the operator fails to take the approach you have suggested, and to suggest that a lock-out or process-lock mechanism might be helpful to prevent such operator error. This would be a bid for user friendliness, and could take the form of a warning message. In other words, should concurrent processes be more "aware" of each other? Today, concurrent processes merely allocate an available tun device, and will attempt to re-use a DNS intercept range that is already in use.

**Comment by qrkourier** [comment]
The state file I was thinking about is `/var/lib/ziti/config.json`. The path is hard-coded and in a directory that is not created by the Linux installation package, and is not writeable by run-as user "ziti", and so the state file is not reliably present on Linux. The tunneler will function without the file, and when the file is present the tunnel will honor setting like log level at a higher precedence than command-line options, which is unexpected.

**Comment by qrkourier** [comment]
I haven't encountered this issue for a long time.
