### ISSUE TITLE
accept enrollment token as env var in Docker container

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#160]
@floucks is looking for functionality to enable providing the token through legacy deployment systems that do not support additional files but do support env vars.

We could invent one additional env var like NF_REG_TOKEN which value is the JWT and continue using the value of NF_REG_NAME to determine the identity config JSON filename.

**Comment by qrkourier** [comment]
@floucks this is the Git repo for the `ziti-edge-tunnel` container, and we'll probably want to do the same thing or something similar here as the changes to [the entrypoint script you mentioned for `ziti-tunnel`](https://github.com/openziti/ziti/blob/release-next/ziti-tunnel/docker/docker-entrypoint.sh).

**Comment by floucks** [comment]
@qrkourier, if I understand correctly, enabling this would require 3 things:
- Adding a new environment variable (NF_REG_TOKEN) to the docker-compose.yml
- Adding the logic to the entrypoint.sh script to handle the new variable and perform enrollment
- Updating docs (developer tools, developer site, and Dockerhub?)

Any other dependencies I'm not thinking of? 

The basic logic I'm thinking in the entrypoint.sh file is: if NF_REG_TOKEN found, don't bother searching for the JWT file...just skip right ahead to enrolling the endpoint using the JWT string directly...thus making the token supplied via environment variable the highest priority option. Nic also sent me some ideas that could streamline the approach without using if/then blocks. 

My week is pretty full but if someone would like me to take a stab at this let me know.

**Comment by floucks** [comment]
Feel free to close in favor of #168.
