### ISSUE TITLE
ziti-edge-tunnel run --identity-dir fails silently

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#174]
Expectation: `ziti-edge-tunnel` notices new identity configuration files by "watching" identity-dir OR fails audibly at startup because there are zero identity files to load in identity-dir.

Observation: `ziti-edge-tunnel` starts without error when there are zero identity files in identity-dir and never notices newly-appeared identity configuration files in identity-dir.

**Comment by qrkourier** [comment]
```bash
root@kpop4:/# ziti-edge-tunnel version
v0.17.12
```

**Comment by dovholuknf** [comment]
I was going to merge these into one broader 'validation' issue - but in retrospect maybe having them separate has merit.

**Comment by qrkourier** [comment]
I feel more strongly about the silent failure for zero identities when `--identity-dir` is passed. I'm content to require a restart to notice new identities, and to document that the identity dir is not a "hot" folder.

**Comment by qrkourier** [comment]
There's another problem with the way `ziti-edge-tunnel --identity-dir` works. When it encounters a file in the identity dir that it can not load it stops trying to load further identities. It should instead ignore invalid files.

**Comment by qrkourier** [comment]
Now `ziti-edge-tunnel` legitimately starts when no identities are loaded because they may be hot swapped later via IPC commands.
