### ISSUE TITLE
USR1 fails to write debug state file

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#176]
Sending signal USR1 to `ziti-edge-tunnel` v0.17.12 triggers this log message, and `/tmp` exists and is mode 1777, but the ~~core dump~~ debug state file never appears.

It's not clear if `12` is the expected to be the PID, but in this case PID 12 is another process.

```bash
❯ ps -fww 12                                                                                                    
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root          12       2  0 Jul11 ?        S      0:05 [ksoftirqd/0]

❯ pgrep -f ziti-edge-tunnel.*identity-dir|xargs ps -fww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root     1819766 1819747  0 09:49 pts/0    Sl+    0:14 ziti-edge-tunnel run --identity-dir /ziti-edge-tunnel --verbose=4 --dns-ip-range=100.64.128.0/18

❯ sudo kill -USR1 1819766
```

gets log line like

```
[      257.227]    INFO lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c:468 on_sigdump() saving Ziti dump to /tmp/ziti-dump.12.dump
```

**Comment by ekoby** [comment]
Note: `ziti dump` does not generate core file. it outputs internal state of the application for debugging purposes

**Comment by qrkourier** [comment]
In this case I attempted to create core file by sending signal USR1. Is that the correct procedure?

**Comment by ekoby** [comment]
> In this case I attempted to create core file by sending signal USR1. Is that the correct procedure?

https://stackoverflow.com/questions/68160/is-it-possible-to-get-a-core-dump-of-a-running-process-and-its-symbol-table/68190

**Comment by ekoby** [comment]
can you try with binary from here https://github.com/openziti/ziti-tunnel-sdk-c/actions/runs/1045646809

**Comment by qrkourier** [comment]
@ekoby Thank you for clarifying that. I was confused about the difference between a core dump file and a Ziti dump debug state file. I was trying to create the debug state file by sending signal USR1.

**Comment by qrkourier** [comment]
@ekoby I was unable to reproduce the problem with the binary build you prescribed. The debug state dump file appears normal with that build.
