### ISSUE TITLE
ziti-edge-tunnel enroll fails silently if missing required params

### ISSUE THREAD

**Issue by mguthrie88** [openziti/ziti-tunnel-sdk-c#320]
Running:
`./ziti-edge-tunnel enroll -j ./my_identity.jwt`
 silently fails with no output. (command is missing the -i flag for the output file)

Should have some basic validation around commands so if required args are missing that you get usage suggestions printed back to you.

**Comment by dovholuknf** [comment]
duplicate of https://github.com/openziti/ziti-tunnel-sdk-c/issues/174

**Comment by dovholuknf** [comment]
v
