### ISSUE TITLE
ZET Help menu still shows -n option

### ISSUE THREAD

**Issue by dariuszSki** [openziti/ziti-tunnel-sdk-c#355]
It looks like the help menu still show the old config option "n" - https://github.com/openziti/ziti-tunnel-sdk-c/blob/main/programs/ziti-edge-tunnel/ziti-edge-tunnel.c
![image](https://user-images.githubusercontent.com/25620231/168617194-e086a961-ab43-491e-9290-60496bce6451.png)
![image](https://user-images.githubusercontent.com/25620231/168617675-3f307f62-6925-448b-9bc8-560f242ab2ab.png)

**Comment by qrkourier** [comment]
Fixed
