### ISSUE TITLE
ziti-edge-tunnel assumes it is the only instance

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#395]
```
[        0.001]   ERROR ziti-edge-tunnel:instance-config.c:121 save_tunnel_status_to_file() Could not save the config file [/var/lib/ziti/config.json] due to semaphore lock not initialized error.
```

It's not clear if this is a fatal error, or what might happen if multiple tunnelers are running with discrete IP ranges or without any IP range in the case of `ziti-edge-tunnel run-host` mode.

It's not clear what is the relationship between ziti-edge-tunnel and /var/lib/ziti/config.json, but `ziti-edge-tunnel run-host` certainly lacks permission to write this file.

**Comment by dovholuknf** [comment]
It's still expected that there are only one ziti-edge-tunnel instance running on any given machine. This issue looks like it comes down to a programming error but is related to using `-i` vs `-I`... `-I` doesn't see this particular error. This should be fixed in the upcoming release
