### ISSUE TITLE
tunneler somehow corrupting ztAPI during ip->dns migration

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-tunnel-sdk-c#400]
many users have had their ZDEW crash over and over. When looking at the identity it had an invalid ztAPI. I saw one ztAPI that looked like a posture check, and this ztAPI is just totally garbage. review the code and determine if there's a memory access issue

![image](https://user-images.githubusercontent.com/46322585/174941637-5ae21a4f-a291-4036-b5e6-ec5ddeabb8e5.png)

**Comment by ekoby** [comment]
fixed in #425
