### ISSUE TITLE
build broken for gcc5 in release 0.19.0

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#450]
https://github.com/openziti/ziti-tunnel-sdk-c/runs/7416143104?check_suite_focus=true

**Comment by qrkourier** [comment]
Comments received include:
> the build issue is actually in the csdk, and it's a c++ file ((zitify). c++ language features can be hard to support with very old compilers.

**Comment by ekoby** [comment]
update to ziti-sdk-c@0.29.3: zitify was promoted to its own repo

**Comment by scareything** [comment]
We updated to 0.29.3 with #458. Can this be closed?
