### ISSUE TITLE
segfault when ziti-edge-tunnel run-host v0.19.2

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#454]
I'm getting an immediate segfault with no output for any log level when I run ziti-edge-tunnel v0.19.2 like this:

```bash
/opt/openziti/bin/ziti-edge-tunnel run-host --identity ./bingnet-jellyfin-host.json --verbose=4
```

[valgrind.log](https://github.com/openziti/ziti-tunnel-sdk-c/files/9174671/valgrind.log)

I'll send the CoreDump file privately.

**Comment by dovholuknf** [comment]
should be fixed with https://github.com/openziti/ziti-tunnel-sdk-c/pull/455/files

**Comment by dovholuknf** [comment]
also - I think you can work around this by using `-I` until fixed
