### ISSUE TITLE
SegFault with ziti-edge-tunnel-Linux_arm64 v0.19.2

### ISSUE THREAD

**Issue by 0xE282B0** [openziti/ziti-tunnel-sdk-c#456]
Hi,
I tried the linux edge tunnel on ARM64 (Oracle Cloud VM/local multipass VM), but I got a `Segmentation fault` on `/ziti-edge-tunnel run-host`.
You can find the details in discourse: https://openziti.discourse.group/t/segfault-with-linux-edge-on-oracle-cloud-vm/675

This only affects v0.19.2, version v0.19.0 is working on oracle cloud and in the local VM.
On my RaspberryPi4 v0.19.2 is running fine.

**Comment by dovholuknf** [comment]
I just published 0.19.3. it should fix this problem. 

https://github.com/openziti/ziti-tunnel-sdk-c/tree/v0.19.3

Bug here:
https://github.com/openziti/ziti-tunnel-sdk-c/issues/454

**Comment by 0xE282B0** [comment]
@dovholuknf, thanks `v0.19.3` works fine for me.
