### ISSUE TITLE
ZITI-EDGE-TUNNEL: Help Menu Duplication Display

### ISSUE THREAD

**Issue by NicFragale** [openziti/ziti-tunnel-sdk-c#462]
When asking for help with “-h”, the usage menu is displayed twice.

ZET Version 0.19.6

![zet-help](https://user-images.githubusercontent.com/29712400/181619596-3cf04f79-df2a-4d3b-a5fd-246a700344ae.png)

**Comment by dovholuknf** [comment]
this will be fixed in whenever the next release happens. the dependency was updated to not duplicate the message.
