### ISSUE TITLE
log doesn't rotate on the end of month

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-tunnel-sdk-c#486]
log_utils.c has a problem on end of month. it uses tm_mday to determine if a log roll should occur and at the end of the month the day will be 28/29/30/31 of the 'orig_time' and the next time will be 1 since its' the "day in the month". The logs are still there, but the log file doesn't rotate.

Fix that. See line 112 ish:
```
        if (orig_time->tm_mday < tm->tm_mday) {
```

**Comment by RAYANI630** [comment]
Assign me this issue. I'll try to resolve it.

**Comment by dovholuknf** [comment]
Go for it! You can see that on days 28/29/30/31, the next day of the month is 1, and thus that boolean won't be true.

**Comment by RAYANI630** [comment]
Will try to generate pr on 1st Oct.

**Comment by dovholuknf** [comment]
Excellent. Thanks!

**Comment by szymonnogiec** [comment]
Hey, since RAYANI630 hasn't created any PR, I've fixed that https://github.com/openziti/ziti-tunnel-sdk-c/pull/547
