### ISSUE TITLE
Unable to access service: service xxx has no terminators for instanceId xxx

### ISSUE THREAD

**Issue by theheckwr** [openziti/ziti-tunnel-sdk-c#508]
Using the compiled ziti-edge-tunnel binary on Manjaro to connect to a service leads to a connection error and logging the following lines:
```
[       76.038]    INFO tunnel-cbs:ziti_dns.c:506 format_resp() found record[100.64.0.4] for query[1:<address>]
[       76.183]   ERROR ziti-sdk:connect.c:941 connect_reply_cb() conn[0.0/Connecting] failed to connect, reason=service <serviceid> has no terminators for instanceId <identity>
[       76.183]   ERROR tunnel-cbs:ziti_tunnel_cbs.c:104 on_ziti_connect() ziti dial failed: connection is closed
```
However the same service is accessible using the Android tunneler app.
- Environment: Manjaro (Kernel: 5.19.7-1-MANJARO)
- Using the latest ziti-edge-tunnel binaries (v0.19.11-local) and compiling it from main (v0.19.11-1-g971f4fc)

Some additional info:
I can see terminators getting created in the ZAC when I update the services.
But the issue on the client tunneler's side still persists.

**Comment by dovholuknf** [comment]
Hi @theheckwr . Thanks for the report. This could be a policy issue. If you run `ziti edge policy-advisor identities` does your identity have dial capability? I'm thinking it might have bind but not dial?

**Comment by scareything** [comment]
If the policy check doesn't turn up anything, could you also please share your service configurations, and show a list of terminators at the time the dial fails?

**Comment by theheckwr** [comment]
I checked the policy advisor and everything looks fine.
As for the service configuration, this is what I'm able to dump via the CLI:
![image](https://user-images.githubusercontent.com/22587394/194412811-98147c79-a9e1-4a48-9a4c-da4f749babc4.png)

The terminators at the time of the dial failure:
![2022-10-06_22-19](https://user-images.githubusercontent.com/22587394/194411926-d9890510-9e0e-4fdd-80c5-7f107575bbf0.png)

In the case it matters: I only did the dumps with the CLI, for the configuration I used the ZAC.
Thanks in advance.

**Comment by scareything** [comment]
Thanks for the info! I was hoping to see the actual service configuration (json), e.g. via `ziti show config`:

     ziti show config 3d7TgvPfhSC1RfiFrgsBx3
     ziti show config 658owvlrnClMBJgZEbVuZ8

Feel free to sanitize the content to your liking. I'm mostly interested in the dialOptions.identity value from the intercept.v1, and the listenOptions.identity value from the host.v1.

Thanks!

**Comment by theheckwr** [comment]
Oh okay, I'm new to ZITI, so I don't know all the different sections that well.
But here are the results of the two commands you asked for:
![image](https://user-images.githubusercontent.com/22587394/194417150-b51e8225-8a48-4eac-8ec6-6d9ca90c8d21.png)
![image](https://user-images.githubusercontent.com/22587394/194417697-bcd27e73-b660-4097-ac1b-3c0e812486c1.png)
Does this help or did I sanitize too much?
If I can help with anything else, don't hesitate to ask again.

**Comment by dovholuknf** [comment]
Given the displayed hosting config has no "listenOptions" set - it seems like it's a sure thing that really what @theheckwr wants is to remove that "identity" from dialOptions. :)

And - we found a bug in the android tunneler !

**Comment by dovholuknf** [comment]
Android bug filed https://github.com/openziti/ziti-sdk-android/issues/2

**Comment by theheckwr** [comment]
Huge thanks to you both!
Yes, removing the `dialOptions.identity` did bring the two services to life.
Somehow the ZAC dialog led me down the wrong path and I wasn't able to track that issue down.
With the Android bug filed, I'm closing this issue.
Thanks again.

**Comment by dovholuknf** [comment]
If you have a flow in the zac that would have helped you or made more sense - and want to file an enhancement request over at https://github.com/openziti/ziti-console that'd be much appreciated. tell us how we could have made it better/easier :)

glad you're sorted!
