### ISSUE TITLE
ziti-edge-tunnel should prefer NetworkManager mode on newer Red Hat distributions

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#527]
The symptom is `ziti-edge-tunnel run` falls back to directly manipulating `/etc/resolv.conf` file. This allows Ziti DNS to function initially, but is not ideal.

**Comment by qrkourier** [comment]
This is an enhancement, not a bug, because we haven't yet developed a solution for the default Red Hat resolver configuration. One way for a consumer to address is to install and enable `systemd-resolved` before running the OpenZiti tunneler. 

In a spot check of a RedHat 9 system I can see that `/etc/resolv.conf` is a regular file, not a symlink, and systemd-resolved is not installed. Network Manager is enabled.

```bash
[rocky@ip-172-31-4-195 ~]$ nmcli c s System\ eth0 | grep IP4.DNS
IP4.DNS[1]:                             172.31.0.2

[rocky@ip-172-31-4-195 ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
search us-west-1.compute.internal
nameserver 172.31.0.2

[rocky@ip-172-31-4-195 ~]$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.0 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.0"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"

```

**Comment by sabedevops** [comment]
Should we support the default resolver configuration or encourage users to enable and start `systemd-resolved` on those distributions to interoperate with the `ziti-edge-tunnel`? If `/etc/resolv.conf` is a regular file, then the fallback towards direct manipulation should be harmless on a default distribution; however, NetworkManager can operate in other modes as well and we should understand the default mode for the RHEL systems.
