### ISSUE TITLE
ziti-edge-tunnel run ignores --verbose=N

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#531]
Expected: only log messages at level INFO or lower
Observed: log messages from levels: ERROR, WARN, INFO, DEBUG, VERBOSE, TRACE

```bash
/opt/openziti/bin/ziti-edge-tunnel run --verbose=2 --dns-ip-range=100.64.0.2/12 --identity-dir=/opt/openziti/etc/identities
```

```bash
❯ apt show ziti-edge-tunnel
Package: ziti-edge-tunnel
Version: 0.20.5
Priority: optional
Section: devel
Maintainer: support@netfoundry.io
Installed-Size: 5,707 kB
Depends: iproute2, sed, systemd, libatomic1, openssl
Download-Size: 2,385 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.openziti.org/zitipax-openziti-deb-stable jammy/main amd64 Packages
Description: ziti-tunnel-sdk-c built using CMake
```

**Comment by qrkourier** [comment]
I found the list of log levels by parsing the output from `ziti-edge-tunnel run` from the systemd journal.

```bash
❯ journalctl -u ziti-edge-tunnel.service | awk '{print $8;}' | sort -u | grep -E '^[A-Z0-9]+$'
DEBUG
ERROR
INFO
TRACE
VERBOSE
WARN
```

**Comment by scareything** [comment]
you need to specify `--verbose N`

**Comment by qrkourier** [comment]
@scareything I get the same log levels when I replace the `=`-separated params with spaces. I get the same result with `--verbose 4` as `--verbose 2`.

```bash
❯ sudo /opt/openziti/bin/ziti-edge-tunnel run --verbose 2 --dns-ip-range 100.64.0.2/12 --identity-dir /opt/openziti/etc/identities 2>&1 | head -999 | awk '{print $3;}' | sort -u | grep -E '^[A-Z0-9]+$'
DEBUG
INFO
TRACE
VERBOSE
^C
```

**Comment by qrkourier** [comment]
Now I think I'm simply seeing a continuation of the same problem described in https://github.com/openziti/ziti-tunnel-sdk-c/issues/385 i.e. the precedence of the config.json file is higher than command line opt `--verbose N`. This means the tunneler always logs at whatever log level was specified the first time it ran when the config.json file was created.

**Comment by johnalotoski** [comment]
I probably also ran into this issue and noted related behavior in the discussion here:
https://openziti.discourse.group/t/misc-notes-after-a-few-days-of-working-with-ziti/826/1

**Comment by qrkourier** [comment]
My new preferred workaround for the unexpected problem of the config file having a higher precedence than the command-line option and environment variables is to set the log level with an IPC command.

```bash
ziti-edge-tunnel set_log_level --loglevel TRACE
```
