### ISSUE TITLE
ziti-edge-tunnel does not always recover from ISP failure

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#551]
I'm running `ziti-edge-tunnel` 0.20.9 and I've noticed that it's sometimes necessary to restart the process after a temporary loss of internet access. I've observed this with both `run` and `run-host` modes.

Both `run` and `run-host` display error messages about the controller being unavailable.

The symptom on the client side is a TCP connection refused although the Ziti nameserver continues to resolve names.

**Comment by dovholuknf** [comment]
are you saying you consider this a regression? or did you reference the version just as information?

**Comment by qrkourier** [comment]
I didn't judge it to be a regression necessarily. I've experienced this for quite some time but not so frequently that I thought it was a bug. I definitely observed the same problem recently in 0.20.7 and wanted to make sure it was still happening in 0.20.9 before I reported it.

I determined that the internet was temporarily inaccessible by attempting to `curl` the `ztApi` URL from the config and got a timeout. Then, when I verified the controller was accessible with the same command but the tunneler kept saying it was unavailable.

I'm running `ziti-edge-tunnel run` installed from the Ubuntu Jammy repo (the OpenSSL build) and I'm running `run-host` in the `openziti/ziti-edge-tunnel:0.20.9` container (uses the Mbed-TLS build).

**Comment by qrkourier** [comment]
```
Nov 12 16:44:13 kpop4 ziti-edge-tunnel[633689]: (633689)[      668.256]   ERROR ziti-sdk:ziti_ctrl.c:154 ctrl_resp_cb() ctrl[17ba74fe-afff-4d4d-aa69-c915c4d3aecf.production.netfoundry.io] request failed: -103(software caused connection abort)
Nov 12 16:44:13 kpop4 ziti-edge-tunnel[633689]: (633689)[      668.256]   ERROR ziti-sdk:ziti_ctrl.c:154 ctrl_resp_cb() ctrl[17ba74fe-afff-4d4d-aa69-c915c4d3aecf.production.netfoundry.io] request failed: -103(software caused connection abort)
Nov 12 16:44:13 kpop4 ziti-edge-tunnel[633689]: (633689)[      668.256]   ERROR ziti-sdk:ziti.c:1052 update_services() ztx[0] failed to get service updates err[CONTROLLER_UNAVAILABLE/software caused connection abort] from ctrl[https://17ba74fe-afff-4d4d-aa69-c915c4d3aecf.production.netfoundry.io:443]
```

**Comment by ekoby** [comment]
can you collect higher level logging, including `uv-mbed` by setting UV_MBED_DEBUG environment variable

**Comment by qrkourier** [comment]
Potentially related to https://github.com/openziti/ziti-tunnel-sdk-c/issues/573

**Comment by qrkourier** [comment]
I was not able to reproduce this problem with 0.22.7. To simulate the ISP failure, I added a traffic control qdisc with 100% packet loss, waited a few seconds for a Ziti service to stop functioning, then deleted the qdisc, waited a few seconds for the Ziti service to resume functioning.

```
sudo tc qdisc add dev wlp3s0 root netem loss 100%
sudo tc qdisc del dev wlp3s0 root netem loss 100%
```
