### ISSUE TITLE
How to configure log timestamp?

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#569]
`ziti-edge-tunnel run` and `run-host` emit log messages prefixed with a timestamp expressed as `ss.ms` elapsed since the process started. It would be convenient for comprehending logs if the timestamp conformed to a readable datetime standard like IS8601, or perhaps another standard that expresses milliseconds. Is there a way to influence the format of this field? I did try setting `PFXLOG_NO_JSON="true"` just in case that would have an effect.

**Comment by dovholuknf** [comment]
you're asking for when you're not using journald i assume, and when you're just running it directly? `PFXLOG_NO_JSON` is not relevant to the ziti-edge-tunnel

**Comment by qrkourier** [comment]
Correct, and I see what you mean. `systemd-journald` interprets the `ss.ms` output and prints a readable datetime like `Dec 05 12:59:24`. My `run-host` deployments aren't managed by `systemd`, and so there's no interpretation of the `ss.ms` value in messages to stdout.

**Comment by dariuszSki** [comment]
@ekoby @scareything can we implement this? I am troubleshooting a problem and this option would be useful when  a user redirect stdout/err to a file.  This is the case now with this user. It is difficult to correlate the errors generated by ZET to errors seen by the rest of the networks like ERs/Controller.

**Comment by ekoby** [comment]
It's already available. Set environment variable `ZITI_TIME_FORMAT=utc`
