### ISSUE TITLE
Wildcard services not properly mapping port in range

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-tunnel-sdk-c#578]
see https://openziti.discourse.group/t/interesting-issue-with-multiple-networks/956/7

User has a wildcard service and other services defined along with a port range defined on the wildcard service. The logs very clearly show:

* each service is being processed by the tunneler properly and IP is assigned. 
* `stafford.esxi` is assigned IP 100.64.0.4
* a request comes in for `matching domain[*.cla.local] found for tnas001.cla.local`
* the tunneler processes the wildcard match and assigns `tnas001.cla.local -> 100.64.0.22`
* tunneler correctly returns 100.64.0.22 to the DNS response
* intercepts the proper IP with on the proper port, but then mismaps the service entirely and dials the wrong service

**Comment by scareything** [comment]
When matching wildcard domain addresses, we were using the address matching function from ziti-sdk-c incorrectly. The matching function returns a score where -1 is a mismatch, 0 is an exact match, and larger integers are lesser matches, but the return value was being interpreted as boolean.

This caused matches on wildcard domains to incorrectly be counted as matching when compared against plain hostname addresses.
