### ISSUE TITLE
terminate existing connections after calling ziti_tunneler_stop_intercepting

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-tunnel-sdk-c#58]
Today I had:
* setup a service and established an ssh session to 192.168.15.3 successfully:
`  INFO    ziti-tunnel-sdk-c:lib/tunnel_tcp.c:375 recv_tcp(): intercepted connection to 192.168.15.3:22 from client tcp:100.64.0.1:1040 for service clint-ssh-hosted-ipsvc
`
* 'stopped' intercepting:
`  [       96.904] INFO    ziti-tunnel-sdk-c:lib/intercept.c:58 remove_intercept(): removing intercept 192.168.15.3:22 for service clint-ssh-hosted-ipsvc (id l3S29D2Gg)
`
* ssh continued to function - i expected to be disconnected immediately
* exited ssh
* tried to connect to ssh - could not connect as expected:
`  [      158.801] DEBUG   ziti-tunnel-sdk-c:lib/tunnel_tcp.c:331 recv_tcp(): no v1 intercepts match 192.168.15.3:22
`

**Comment by scareything** [comment]
this issue can also cause garbled log output when the existing sessions are finally closed:

    [2020-11-25T00:35:11.869Z] INFO	ziti-tunnel-sdk-c:lib/ziti_tunnel.c:176 ziti_tunneler_close(): closing connection: service=K��, client=tcp:100.64.0.1:56920

**Comment by scareything** [comment]
closed by #70
