### ISSUE TITLE
Segfault of MacOS ZET triggered by no connection traffic

### ISSUE THREAD

**Issue by smilindave26** [openziti/ziti-tunnel-sdk-c#601]
not sure if this is ziti-edge-tunnel issue or ziti-sdk-c, but will start it off here...

See Discourse post https://openziti.discourse.group/t/segfault-of-macos-zet-triggered-by-no-connection-traffic/1098

**Comment by ekoby** [comment]
ziti-sdk fix: https://github.com/openziti/ziti-sdk-c/pull/492
ziti-tunnel-sdk update: #605
