### ISSUE TITLE
DNS resolver detection is flawed when resolv.conf is a regular file

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti-tunnel-sdk-c#613]
In cases where `/etc/resolv.conf` is a regular file, but `org.freedesktop.resolve1` is an _acquired_ name in `dbus`, the resolution will always configure `systemd-resolved` as if it was the primary resolver on the system. 

This assumption is valid in the container case, where `/etc/resolv.conf` is a regular file and the dbus socket is mounted from the host filesystem. On systems where `/etc/resolv.conf` was potentially clobbered by an errant `sed -i`, the tunneler's auto-configuration scheme is insufficient. 

We may want to drive this via an environment variable or CLI flag instead so that the detection logic behavior can be adjusted when the overall system state cannot be determined purely through introspection (as may be the case inside of a container).

**Comment by qrkourier** [comment]
This may be moot because ZET normally runs-as user "ziti" and doesn't have permission to munge `/etc/resolv.conf`. We might decide to find a way to allow that. Here's [a place for discussing it](https://github.com/openziti/ziti-tunnel-sdk-c/issues/642).

**Comment by sabedevops** [comment]
With PRs #674 (we no longer clubber the symlink) and #614, this should indeed be moot for all intents and purposes.
