### ISSUE TITLE
prerelease to downstreams on Git release tags and manually trigger promoting downstreams

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#730]
We have a couple of options for making prerelease RPM, DEB available to beta testers:

1. publish to parallel code-name trees like `jammy-test` in the main parent repo resulting in Apt sources like `deb [signed-by=/usr/share/keyrings/openziti.gpg] https://packages.openziti.org/zitipax-openziti-deb-stable jammy-test main`
2. ~~publish to alternative parent repo with code-name trees like `jammy` resulting in Apt sources like `deb [signed-by=/usr/share/keyrings/openziti.gpg] https://packages.openziti.org/zitipax-openziti-deb-test jammy main`~~

This facilitates a pattern of making prereleases accessible to a broader audience and gathering more feedback before release.

**Comment by qrkourier** [comment]
I prefer the first option because of the existing pattern throughout the OpenZiti org's GitHub CI of uploading all deb packages to the same Artifactory repo, and all rpm packages to the same Artifactory repo, but separating release and prerelease by object key prefix, so as to create discrete Apt and Yum repos.

This pattern allows me to test package CI in my GitHub fork where I upload to the alternative Artifactory repos, and can mirror the release/prerelease behaviors without impacting users.

**Comment by qrkourier** [comment]
We'll adopt a more modular, manually triggered release procedure for now.

Merging to main will continue to draft the GitHub release description, which does not create a Git tag but summarizes commits according to a template.

The releaser person will use the `gh` CLI or GitHub.com to create a Releases API object with a semver `tag_name` and `prerelease: true` from the automatically-drafted release. This creates a set of immutable release candidate artifacts by manually triggering the release workflow for each artifact in the release set: 

1. Docker: a semver-tagged container image in Hub (but not `:latest`),
1. CMake: binaries in GitHub releases that are not yet visible to the public, and
1. CPack: RPMs and DEBs are uploaded to a prerelease repository in Artifactory where only beta testers are subscribed.

At this stage, the burn-in, beta-testing period of arbitrary length begins.

The final step is to promote a set of release candidate artifacts. This is triggered manually by the following steps. In the Releases API via GitHub.com or the `gh` CLI, the releaser person sets `prerelease: false` on the release. This causes it to be included in the set of releases considered when computing the latest release highlighted on GitHub.com. As an aside, it is never necessary to manually set "make latest" (`make_latest: true`) while creating a release object unless you specifically need to override the default algorithm for computing the latest release by creation date and semver.

Now the same three release workflows are triggered. They take a different set of actions based on whether there is a release object with the same `tag_name` as the commit SHA on which they are triggered that exactly matches a release with `prerelease: false`.

1. Docker: the multi-platform, semver-tagged container image in Hub is tagged  `:latest` (`buildx imagetools create --tag`),
1. CMake: binaries in GitHub releases becomes visible to the public by setting `prerelease: false` in Releases API, and
1. CPack: RPMs and DEBs are promoted to the release repository in Artifactory where the public is subscribed (`jf rt cp`).

**Comment by ekoby** [comment]
is this true?
> CMake: binaries in GitHub releases that are not yet visible to the public, and

for the final step:
>the same three release workflows are manually triggered

maybe add a `promote` workflow that calls these three release steps, to eliminate human error

**Comment by qrkourier** [comment]
> is this true?
> 

No, I was mistaken. The prereleases are labeled with a yellow `prerelease` pill in GitHub.com and are visible to the public.

**Comment by qrkourier** [comment]
> maybe add a `promote` workflow that calls these three release steps, to eliminate human error

I favor the idea of automating the triggers for the same reason. It is an optimization that is easily added after this intial implementation, especially if there's not unanimity about automating triggers. That is, we can be a bit more conservative at first and trigger the prerelease and release workflows manually, then decide to automate as confidence is rebuilt.

**Comment by qrkourier** [comment]
I'm implementing this now based on the sketch and feedback in this issue.

**Comment by qrkourier** [comment]
#### New sketch

1. Releaser freezes changes by manually creating a permanent Git tag with GitHub Releases (audit the draft, etc.).
2. This triggers workflows - CI Build, CI Package, and Publish Containers which build artifacts, but only CI build (binaries for each platform) uploads artifacts to the GitHub release page.
3. Later, a releaser manually triggers an new workflow, e.g., "Promote Downstream Releases." This workflow makes Hub, Artifactory uploads "latest" by running on a semver Git tag and calculating the artifact names to promote. The artifacts are not re-built, but promoted, in those downstreams.

**Comment by qrkourier** [comment]
Importantly, this approach decouples the downstream repositories notion of "latest" from GitHub Releases notion of "latest" vs. "prerelease." Put another way, the GitHub release can be (un)marked prerelease or latest at will, and the downstream promotion to "latest" is always a manually-triggered event, not one that occurs automatically based on the GitHub release being marked one way or the other.

**Comment by qrkourier** [comment]
> ## Releaser procedure
>
>1. [Create a release in GitHub](https://github.com/openziti/ziti-tunnel-sdk-c/releases).
>1. Run ["Promote Downstream Releases"](https://github.com/openziti/ziti-tunnel-sdk-c/actions/workflows/promote-downstreams.yml) on the release tag you created in the first step.

from: https://github.com/openziti/ziti-tunnel-sdk-c/blob/prerelease-downstreams/RELEASING.md
