### ISSUE TITLE
tunnel SIGSEGV 

### ISSUE THREAD

**Issue by xuacker** [openziti/ziti-tunnel-sdk-c#731]
the code on line 262 of this file https://github.com/openziti/ziti-tunnel-sdk-c/blob/main/lib/ziti-tunnel-cbs/ziti_hosting.c should be changed from "if (dial_protocol_str == NULL | dial_protocol_str[0] == '\0')" to "if (dial_protocol_str == NULL || dial_protocol_str[0] == '\0')".

**Comment by scareything** [comment]
thanks for catching this and letting us know!
