### ISSUE TITLE
docker images latest and 1.1.0 GLIBC_2.29 not found

### ISSUE THREAD

**Issue by franciscsimon** [openziti/ziti-tunnel-sdk-c#921]
Hey,

on the latest docker image and the version 1.1.0:

- `docker run --rm --entrypoint bash openziti/ziti-edge-tunnel -c "ziti-edge-tunnel version"`
- `docker run --rm --entrypoint bash openziti/ziti-edge-tunnel:1.1.0 -c "ziti-edge-tunnel version"`

i get an error message:

`ziti-edge-tunnel: /lib64/libm.so.6: version GLIBC_2.29 not found (required by ziti-edge-tunnel)`

BR Frank ;-)

**Comment by scareything** [comment]
Hi,

We recently needed to update the GitHub runners that we use for release builds from ubuntu 18 to ubuntu 20. This is the reason for the missing glibc dependency that you are seeing.

Two paths around this for you are:
1. update your docker host to a newer ubuntu/debian version.
2. if updating the host is not an option, you could build ziti-edge-tunnel on your own ubuntu 18 host.

**Comment by qrkourier** [comment]
@scareything The container image has a glibc version that's too old for the binary after we upgraded the builder image.

```bash
❯ docker run --rm --entrypoint= openziti/ziti-edge-tunnel:1.1.0 ziti-edge-tunnel version
ziti-edge-tunnel: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ziti-edge-tunnel)

❯ docker run --rm --entrypoint= openziti/ziti-edge-tunnel:1.1.0 ldd --version
ldd (GNU libc) 2.28
```

**Comment by qrkourier** [comment]
Sent a PR to bump the runner image from RedHat8  (glibc 2.28) to RedHat 9 (glibc 2.34).

Test image:

```bash
❯ docker run --rm --entrypoint= kbinghamnetfoundry/ziti-edge-tunnel:1.1.0-newer-glibc ziti-edge-tunnel version
v1.1.0

❯ docker run --rm --entrypoint= kbinghamnetfoundry/ziti-edge-tunnel:1.1.0-newer-glibc ldd --version           
ldd (GNU libc) 2.34
```

**Comment by bengcooper** [comment]
Can the containers for v1.1.0/latest be re-generated? The publicly available containers still give this issue when trying to run them.

**Comment by dovholuknf** [comment]
we'll take a look today. thanks for the poke.

**Comment by bengcooper** [comment]
Can confirm v1.1.1 is working as expected, thanks!
