### ISSUE TITLE
[Proposal] Linux static executable releases

### ISSUE THREAD

**Issue by nenkoru** [openziti/ziti-tunnel-sdk-c#938]
Hello there!

I was working on integrating tunneler into Talos Linux and after a discussion on a review it seems like it would be a good idea to provide static binaries for Linux on the Releases page.

PR where discussion happened: https://github.com/siderolabs/extensions/pull/454

~~I could work on this if the proposal's gist is accepted.~~
Linked a PR adding statically linked builds.

**Comment by nenkoru** [comment]
need help in that PR
can't force cmake to generate a path to a static version of libpthread instead of a dynamic one
https://github.com/nenkoru/ziti-tunnel-sdk-c/actions/runs/10434844845/job/28898173185

**Comment by qrkourier** [comment]
This was done.
