### ISSUE TITLE
update Linux package-builder images for v2

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#965]
The default branch "main" represents future v2. Linux static binaries are building, but Linux packages are not. The Dockerfile for each CPack builder image needs to be updated for v2. Most target distributions should dynamically link to libssl, but the oldest target distros must statically link libssl because their installed version is ancient libssl v1, i.e., Ubuntu Focal 20.04 and RedHat 8.

**Comment by scareything** [comment]
FYI we are not building static binaries in `main`. We never got to merging it up from `release-1.x`. Furthermore the static builds in release-1.x were problematic unless the host was running a 6.5+ kernel.
