### ISSUE TITLE
RPM identities advisory should be less eager

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti-tunnel-sdk-c#995]
[This change](https://github.com/openziti/ziti-tunnel-sdk-c/commit/e9c1a8ef30e65e58acc015f1f27bea0aa9dc9d19#diff-976db0505aa38d09e615a750ff85ddf4f6b59cf5cbced4ff5e150a26a5a02f85R22) made the `post.sh` script indiscriminately output the initial identities installation advisory message every time the `ziti-edge-tunnel` package is updated via interactive session. This is just a nitpick, but it's quite jarring when updating the system. 

```bash
--------------------------------------------------------------------------------ziti-edge-tunnel was installed...
First install an OpenZiti identity or enroll token in: /opt/openziti/etc/identities
then start or restart this systemd service unit.
--------------------------------------------------------------------------------
```

Also, it's probably missing a newline before the `ziti-edge-tunnel was installed...` (or maybe just delete that text altogether cause it really doesn't add anything)

**Comment by qrkourier** [comment]
blocked by https://github.com/openziti/ziti-tunnel-sdk-c/issues/965
